### ISSUE TITLE
The "empty metadata case" should be handled more gracefully.

### ISSUE THREAD

**Issue by aknrdureegaesr** [tillsc/multi_markdown#9]
```
$ irb
2.3.3 :001 > require 'rmultimarkdown'
 => true 
2.3.3 :002 > m = MultiMarkdown.new "\n\n# Markdown without metadata."
 => #<MultiMarkdown:0x0055bf3e206608> 
2.3.3 :003 > m.metadata
ArgumentError: NULL pointer given
	from /home/andreask/.rvm/gems/ruby-2.3.3/gems/rmultimarkdown-6.4.0.4/lib/multi_markdown.rb:54:in `extract_metadata_keys'
	from /home/andreask/.rvm/gems/ruby-2.3.3/gems/rmultimarkdown-6.4.0.4/lib/multi_markdown.rb:54:in `metadata'
	from (irb):3
	from /home/andreask/.rvm/rubies/ruby-2.3.3/bin/irb:11:in `<main>'
```

**Comment by tillsc** [comment]
Should be fixed in 6.7.0.2. Thanks for reporting this.
